Build and Push OSM Edge Images to Quay.io (#121)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,7 +13,7 @@ on:
   pull_request:
     branches:
       - main
-      - release-*
+      - release-*-ubi8
     paths-ignore:
       - "docs/**"
       - "**.md"
@@ -134,137 +134,137 @@ jobs:
         with:
           flags: unittests
 
-  imagescan:
-    name: Scan images for security vulnerabilities
-    runs-on: ubuntu-latest
-    env:
-      CTR_TAG: ${{ github.sha }}
-      CTR_REGISTRY: "localhost:5000"
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Build docker images
-        env:
-          DOCKER_BUILDX_OUTPUT: type=docker
-        run: make docker-build-osm
-      - name: Setup Trivy
-        run: make trivy-ci-setup
-      - name: Scan docker images for vulnerabilities
-        run: make trivy-scan-images
+#  imagescan:
+#    name: Scan images for security vulnerabilities
+#    runs-on: ubuntu-latest
+#    env:
+#      CTR_TAG: ${{ github.sha }}
+#      CTR_REGISTRY: "localhost:5000"
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#      - name: Build docker images
+#        env:
+#          DOCKER_BUILDX_OUTPUT: type=docker
+#        run: make docker-build-osm
+#      - name: Setup Trivy
+#        run: make trivy-ci-setup
+#      - name: Scan docker images for vulnerabilities
+#        run: make trivy-scan-images
 
-  e2etest:
-    name: Go test e2e
-    runs-on: ubuntu-latest
-    needs: build
-    strategy:
-      matrix:
-        k8s_version: [""]
-        focus: [""]
-        bucket: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
-        include:
-          - k8s_version: v1.19.11
-            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
-            bucket: ".*"
-          - k8s_version: v1.20.7
-            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
-            bucket: ".*"
-          - k8s_version: v1.21.12
-            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
-            bucket: ".*"
-          - k8s_version: v1.22.9
-            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
-            bucket: ".*"
-          - k8s_version: v1.23.6
-            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
-            bucket: ".*"
-          - k8s_version: v1.24.1
-            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
-            bucket: ".*"
-    env:
-      CTR_TAG: ${{ github.sha }}
-      CTR_REGISTRY: "localhost:5000" # unused for kind, but currently required in framework
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Setup Go
-        uses: actions/setup-go@v3
-        with:
-          go-version-file: go.mod
-          cache: true
-      - name: Build test dependencies
-        env:
-          DOCKER_BUILDX_OUTPUT: type=docker
-        run: make docker-build-osm build-osm docker-build-tcp-echo-server
-      - name: Run tests
-        id: test
-        env:
-          K8S_NAMESPACE: "osm-system"
-        run: go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -installType=KindCluster -kindClusterVersion='${{ matrix.k8s_version }}' -test.timeout 0 -test.failfast -ginkgo.failFast -ginkgo.focus='\[Bucket ${{ matrix.bucket }}\].*${{ matrix.focus }}'
-        continue-on-error: true
-      - name: Set Logs name
-        if: ${{ steps.test.conclusion != 'skipped' }}
-        run: |
-          if [[ -n "${{ matrix.k8s_version }}" ]]; then
-            echo "ARTIFACT_NAME=test_logs_k8s_version_${{ matrix.k8s_version }}" >> $GITHUB_ENV
-          else
-            echo "ARTIFACT_NAME=test_logs_bucket_${{ matrix.bucket }}" >> $GITHUB_ENV
-          fi
-      - name: Upload test logs
-        if: ${{ steps.test.conclusion != 'skipped' }}
-        uses: actions/upload-artifact@v2
-        with:
-          name: ${{ env.ARTIFACT_NAME }}
-          path: /tmp/test**/*
-      - name: Check continue tests
-        if: ${{ steps.test.conclusion != 'skipped' && steps.test.outcome == 'failure'}}
-        run: exit 1
-      - name: Clean tests
-        if: ${{ steps.test.conclusion != 'skipped' }}
-        run: rm -rf /tmp/test*
+#  e2etest:
+#    name: Go test e2e
+#    runs-on: ubuntu-latest
+#    needs: build
+#    strategy:
+#      matrix:
+#        k8s_version: [""]
+#        focus: [""]
+#        bucket: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
+#        include:
+#          - k8s_version: v1.19.11
+#            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
+#            bucket: ".*"
+#          - k8s_version: v1.20.7
+#            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
+#            bucket: ".*"
+#          - k8s_version: v1.21.12
+#            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
+#            bucket: ".*"
+#          - k8s_version: v1.22.9
+#            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
+#            bucket: ".*"
+#          - k8s_version: v1.23.6
+#            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
+#            bucket: ".*"
+#          - k8s_version: v1.24.1
+#            focus: "Test traffic flowing from client to server with a Kubernetes Service for the Source: HTTP"
+#            bucket: ".*"
+#    env:
+#      CTR_TAG: ${{ github.sha }}
+#      CTR_REGISTRY: "localhost:5000" # unused for kind, but currently required in framework
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#      - name: Setup Go
+#        uses: actions/setup-go@v3
+#        with:
+#          go-version-file: go.mod
+#          cache: true
+#      - name: Build test dependencies
+#        env:
+#          DOCKER_BUILDX_OUTPUT: type=docker
+#        run: make docker-build-osm build-osm docker-build-tcp-echo-server
+#      - name: Run tests
+#        id: test
+#        env:
+#          K8S_NAMESPACE: "osm-system"
+#        run: go test ./tests/e2e -test.v -ginkgo.v -ginkgo.progress -installType=KindCluster -kindClusterVersion='${{ matrix.k8s_version }}' -test.timeout 0 -test.failfast -ginkgo.failFast -ginkgo.focus='\[Bucket ${{ matrix.bucket }}\].*${{ matrix.focus }}'
+#        continue-on-error: true
+#      - name: Set Logs name
+#        if: ${{ steps.test.conclusion != 'skipped' }}
+#        run: |
+#          if [[ -n "${{ matrix.k8s_version }}" ]]; then
+#            echo "ARTIFACT_NAME=test_logs_k8s_version_${{ matrix.k8s_version }}" >> $GITHUB_ENV
+#          else
+#            echo "ARTIFACT_NAME=test_logs_bucket_${{ matrix.bucket }}" >> $GITHUB_ENV
+#          fi
+#      - name: Upload test logs
+#        if: ${{ steps.test.conclusion != 'skipped' }}
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: ${{ env.ARTIFACT_NAME }}
+#          path: /tmp/test**/*
+#      - name: Check continue tests
+#        if: ${{ steps.test.conclusion != 'skipped' && steps.test.outcome == 'failure'}}
+#        run: exit 1
+#      - name: Clean tests
+#        if: ${{ steps.test.conclusion != 'skipped' }}
+#        run: rm -rf /tmp/test*
 
-  integration-tresor:
-    name: Integration Test with Tresor, SMI traffic policies, and egress disabled
-    runs-on: ubuntu-latest
-    needs: [build]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Setup Go
-        uses: actions/setup-go@v3
-        with:
-          go-version-file: go.mod
-          cache: true
-      - name: Run Simulation w/ Tresor, SMI policies, egress disabled and reconciler disabled
-        env:
-          CERT_MANAGER: "tresor"
-          BOOKSTORE_SVC: "bookstore"
-          BOOKTHIEF_EXPECTED_RESPONSE_CODE: "0"
-          ENABLE_EGRESS: "false"
-          ENABLE_RECONCILER: "false"
-          PERMISSIVE_MODE: "false"
-          DEPLOY_TRAFFIC_SPLIT: "true"
-          CTR_TAG: ${{ github.sha }}
-          USE_PRIVATE_REGISTRY: "false"
-        run: |
-          touch .env
-          make kind-up
-          ./demo/run-osm-demo.sh
-          go run ./ci/cmd/maestro.go
+#  integration-tresor:
+#    name: Integration Test with Tresor, SMI traffic policies, and egress disabled
+#    runs-on: ubuntu-latest
+#    needs: [build]
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#      - name: Setup Go
+#        uses: actions/setup-go@v3
+#        with:
+#          go-version-file: go.mod
+#          cache: true
+#      - name: Run Simulation w/ Tresor, SMI policies, egress disabled and reconciler disabled
+#        env:
+#          CERT_MANAGER: "tresor"
+#          BOOKSTORE_SVC: "bookstore"
+#          BOOKTHIEF_EXPECTED_RESPONSE_CODE: "0"
+#          ENABLE_EGRESS: "false"
+#          ENABLE_RECONCILER: "false"
+#          PERMISSIVE_MODE: "false"
+#          DEPLOY_TRAFFIC_SPLIT: "true"
+#          CTR_TAG: ${{ github.sha }}
+#          USE_PRIVATE_REGISTRY: "false"
+#        run: |
+#          touch .env
+#          make kind-up
+#          ./demo/run-osm-demo.sh
+#          go run ./ci/cmd/maestro.go
 
-  images:
-    name: Docker Images
-    runs-on: ubuntu-latest
-    if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release-')) && github.event_name == 'push' }}
-    env:
-      DOCKER_USER: ${{ secrets.RELEASE_DOCKER_USER }}
-      DOCKER_PASS: ${{ secrets.RELEASE_DOCKER_PASS }}
-      CTR_REGISTRY: flomesh
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Docker Login
-        run: docker login --username "$DOCKER_USER" --password-stdin <<< "$DOCKER_PASS"
-      - name: Push images with "latest-main" tag
-        env:
-          CTR_TAG: latest-main
-        run: make docker-build-cross
+#  images:
+#    name: Docker Images
+#    runs-on: ubuntu-latest
+#    if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release-')) && github.event_name == 'push' }}
+#    env:
+#      DOCKER_USER: ${{ secrets.QUAY_USERNAME }}
+#      DOCKER_PASS: ${{ secrets.QUAY_ROBOT_TOKEN }}
+#      CTR_REGISTRY: quay.io/flomesh
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#      - name: Docker Login
+#        run: docker login quay.io --username "$DOCKER_USER" --password-stdin <<< "$DOCKER_PASS"
+#      - name: Push images with "latest" tag
+#        env:
+#          CTR_TAG: latest
+#        run: make docker-build-cross
